package kz.smartcarshare.app.ui.theme

import kz.smartcarshare.app.data.Lang

object Strings {
    fun get(lang: Lang, key: String): String {
        val map = when (lang) {
            Lang.KZ -> mapOf(
                "app_title" to "Smart CarShare",
                "register_title" to "Тіркелу",
                "login_title" to "Жүйеге кіру",
                "name" to "Аты-жөні",
                "first_name" to "Аты",
                "last_name" to "Тегі",
                "email" to "Email",
                "phone" to "Телефон нөмірі",
                "password" to "Құпия сөз",
                "register_btn" to "Тіркелу",
                "login_btn" to "Кіру",
                "has_account" to "Аккаунт бар ма? ",
                "no_account" to "Аккаунт жоқ па? ",
                "forgot_password" to "Құпия сөзді ұмыттыңыз ба?",
                "profile_edit" to "Профильді өңдеу",
                "my_trips" to "Менің сапарларым",
                "payment_methods" to "Төлем әдістері",
                "for_business" to "Компания үшін",
                "logout" to "Аккаунттан шығу",
                "language" to "Тіл",
                "ai_chat" to "ЖИ-көмекшіден көлік сұрау",
                "home_greeting" to "Қандай көлік іздеп жүрсіз?",
                "save" to "Сақтау",
                "cancel" to "Бас тарту",
                "send" to "Жіберу",
                "nav_home" to "Басты",
                "nav_chat" to "ЖИ-чат",
                "nav_trips" to "Сапарлар",
                "nav_profile" to "Профиль",
                "no_active_trip" to "Қазір белсенді сапар жоқ",
                "nearby_cars" to "Жақын маңдағы көліктер",
                "available" to "қолжетімді",
                "b2b_prompt" to "Компанияңызға абонемент керек пе?",
                "b2b_sub" to "Қызметкерлерге арналған айлық тариф",
                "seats" to "Орын саны",
                "transmission" to "Беріліс қорабы",
                "fuel" to "Отын түрі",
                "category" to "Санат",
                "rental_format" to "Жалдау форматы",
                "hourly" to "Сағаттық",
                "daily" to "Тәуліктік",
                "add_insurance" to "Сақтандыру қосу",
                "rent" to "Жалдау",
                "confirm_payment" to "Растау және төлем",
                "selected_car" to "ТАҢДАЛҒАН КӨЛІК",
                "autopay_title" to "Автоплатеж қосу",
                "autopay_sub" to "Сома алу/тапсыру уақыты бойынша карта автоматты есептен шығарады",
                "main_card" to "Негізгі карта",
                "change" to "Өзгерту",
                "pre_calculation" to "АЛДЫН АЛА ЕСЕП",
                "tariff" to "Тариф",
                "estimated_price" to "Болжамды баға",
                "insurance" to "Сақтандыру",
                "added" to "Қосылды",
                "none" to "Жоқ",
                "confirm_rental" to "Жалдауды растау"
            )
            Lang.RU -> mapOf(
                "app_title" to "Smart CarShare",
                "register_title" to "Регистрация",
                "login_title" to "Вход в систему",
                "name" to "Имя и фамилия",
                "first_name" to "Имя",
                "last_name" to "Фамилия",
                "email" to "Email",
                "phone" to "Номер телефона",
                "password" to "Пароль",
                "register_btn" to "Зарегистрироваться",
                "login_btn" to "Войти",
                "has_account" to "Есть аккаунт? ",
                "no_account" to "Нет аккаунта? ",
                "forgot_password" to "Забыли пароль?",
                "profile_edit" to "Редактировать профиль",
                "my_trips" to "Мои поездки",
                "payment_methods" to "Способы оплаты",
                "for_business" to "Для бизнеса",
                "logout" to "Выйти из аккаунта",
                "language" to "Язык",
                "ai_chat" to "Запросить авто у ИИ",
                "home_greeting" to "Какое авто ищете?",
                "save" to "Сохранить",
                "cancel" to "Отмена",
                "send" to "Отправить",
                "nav_home" to "Главная",
                "nav_chat" to "ИИ-чат",
                "nav_trips" to "Поездки",
                "nav_profile" to "Профиль",
                "no_active_trip" to "Сейчас нет активных поездок",
                "nearby_cars" to "Машины поблизости",
                "available" to "доступно",
                "b2b_prompt" to "Нужен абонемент для компании?",
                "b2b_sub" to "Месячный тариф для сотрудников",
                "seats" to "Количество мест",
                "transmission" to "Коробка передач",
                "fuel" to "Тип топлива",
                "category" to "Категория",
                "rental_format" to "Формат аренды",
                "hourly" to "Почасовой",
                "daily" to "Суточный",
                "add_insurance" to "Добавить страховку",
                "rent" to "Арендовать",
                "confirm_payment" to "Подтверждение и оплата",
                "selected_car" to "ВЫБРАННЫЙ АВТОМОБИЛЬ",
                "autopay_title" to "Включить автоплатеж",
                "autopay_sub" to "Списание произойдет автоматически по времени сдачи авто",
                "main_card" to "Основная карта",
                "change" to "Изменить",
                "pre_calculation" to "ПРЕДВАРИТЕЛЬНЫЙ РАСЧЕТ",
                "tariff" to "Тариф",
                "estimated_price" to "Примерная стоимость",
                "insurance" to "Страховка",
                "added" to "Добавлена",
                "none" to "Нет",
                "confirm_rental" to "Подтвердить аренду"
            )
        }
        return map[key] ?: key
    }
}
